"""DeepCubeA approximate value iteration training.

Trains a DNN J(s) to approximate the optimal cost-to-go via
batch-update AVI: outer Bellman backup fixes J'(s), inner loop
trains with early stopping on fixed targets.

Loads training data from .npy (generated by deepcubea_generate_data.py).
"""

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from datetime import datetime
from pathlib import Path
from tqdm import tqdm
from config import (
    DEEPCUBEA_LR,
    DEEPCUBEA_BATCH_SIZE,
    DEEPCUBEA_OUTER_ITER,
    DEEPCUBEA_INNER_EPOCHS,
    DEEPCUBEA_INNER_PATIENCE,
    DEEPCUBEA_USE_GPU,
    DEEPCUBEA_TRAIN_DATA_PATH,
    DEEPCUBEA_T_MIN,
    DEEPCUBEA_T_MAX,
    DEEPCUBEA_ONLINE_BATCH,
    DEEPCUBEA_BASE_BATCH,
    DEEPCUBEA_OUTER_SEED,
    DEEPCUBEA_SEED_OVERLAP,
)
from deepcubea_network import (
    encode_batch,
    DeepCubeANetwork,
    N,
    N2,
    INPUT_DIM,
)
from deepcubea_utils import generate_scrambled_states

GOAL_STATE = np.arange(N2, dtype=np.int32)

_DR = np.array([-1, 1, 0, 0])
_DC = np.array([0, 0, -1, 1])


def compute_targets(states, network, device):
    """Compute J'(s) targets for all states using current network.

    J'(s) = 0 for goal state, else min_{legal a} [1 + J(A(s,a))].

    Args:
        states: (B, N2) numpy int32 array.
        network: DeepCubeANetwork on the target device.
        device: torch device.

    Returns:
        (B,) float32 tensor on CPU.
    """
    B = len(states)
    blank_pos = np.argmin(states, axis=1)
    blank_r = blank_pos // N
    blank_c = blank_pos % N

    with torch.inference_mode():
        best_j = np.full(B, np.inf, dtype=np.float32)

        for a in range(4):
            nr = blank_r + _DR[a]
            nc = blank_c + _DC[a]
            legal = (0 <= nr) & (nr < N) & (0 <= nc) & (nc < N)

            if not legal.any():
                continue

            new_idx = nr * N + nc
            legal_idx = np.where(legal)[0]

            next_states = states.copy()
            next_states[legal_idx, blank_pos[legal_idx]] = states[
                legal_idx, new_idx[legal_idx]
            ]
            next_states[legal_idx, new_idx[legal_idx]] = 0

            x = encode_batch(next_states).to(device)
            j_vals = network(x).cpu().numpy()

            best_j[legal] = np.minimum(best_j[legal], j_vals[legal] + 1.0)

    goal_mask = np.all(states == GOAL_STATE, axis=1)
    best_j[goal_mask] = 0.0
    best_j[np.isinf(best_j)] = 0.0

    return torch.from_numpy(best_j).float()


def train():
    device = torch.device(
        "cuda" if DEEPCUBEA_USE_GPU and torch.cuda.is_available() else "cpu"
    )
    print(f"Device: {device}")

    # ── Load base training data (used for mixed sampling) ──
    data_path = Path(DEEPCUBEA_TRAIN_DATA_PATH)
    if data_path.exists():
        base_states = np.load(data_path)
        print(f"Loaded {len(base_states)} base states from {data_path}")
    else:
        base_states = None
        if DEEPCUBEA_BASE_BATCH > 0:
            raise FileNotFoundError(
                f"Base training data not found: {data_path}\n"
                "Run deepcubea_generate_data.py first or set DEEPCUBEA_BASE_BATCH=0."
            )

    # ── Results directory ──
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    results_dir = Path("results") / f"train_{timestamp}"
    models_dir = results_dir / "models"
    imgs_dir = results_dir / "imgs"
    models_dir.mkdir(parents=True, exist_ok=True)
    imgs_dir.mkdir(parents=True, exist_ok=True)
    print(f"Results: {results_dir}")

    # ── Network & optimizer ──
    network = DeepCubeANetwork().to(device)
    optimizer = torch.optim.Adam(network.parameters(), lr=DEEPCUBEA_LR)

    param_count = sum(p.numel() for p in network.parameters())
    print(f"Parameters: {param_count:,}")
    print(f"Training: {DEEPCUBEA_OUTER_ITER} outer × max {DEEPCUBEA_INNER_EPOCHS} inner epochs (patience={DEEPCUBEA_INNER_PATIENCE})")
    print(f"Online: B={DEEPCUBEA_ONLINE_BATCH}  Base: B'={DEEPCUBEA_BASE_BATCH}  Overlap={DEEPCUBEA_SEED_OVERLAP}")

    # ── Training: outer Bellman backup × inner fixed-target SGD ──
    all_losses = []
    outer_boundaries = []
    prev_base_indices = None

    outer_pbar = tqdm(range(1, DEEPCUBEA_OUTER_ITER + 1), desc="Outer", unit=" round")
    for outer_iter in outer_pbar:
        # 1. Online generate B states
        online_states = generate_scrambled_states(
            DEEPCUBEA_ONLINE_BATCH, DEEPCUBEA_T_MIN, DEEPCUBEA_T_MAX,
            seed=DEEPCUBEA_OUTER_SEED + outer_iter,
        )

        # 2. Sample B' base states with overlap
        if base_states is not None and DEEPCUBEA_BASE_BATCH > 0:
            carryover = int(DEEPCUBEA_BASE_BATCH * DEEPCUBEA_SEED_OVERLAP)
            fresh = DEEPCUBEA_BASE_BATCH - carryover
            rng = np.random.default_rng(DEEPCUBEA_OUTER_SEED + outer_iter)
            mask = np.ones(len(base_states), dtype=bool)
            if carryover > 0 and prev_base_indices is not None:
                mask[prev_base_indices[:carryover]] = False
            available = np.where(mask)[0]
            new_idx = rng.choice(available, size=fresh, replace=False)
            if carryover > 0 and prev_base_indices is not None:
                base_idx = np.concatenate([prev_base_indices[:carryover], new_idx])
            else:
                base_idx = new_idx
            prev_base_indices = base_idx
            base_batch = base_states[base_idx]
            train_states = np.concatenate([online_states, base_batch])
        else:
            train_states = online_states

        # 3. Deduplicate + encode
        train_states = np.unique(train_states, axis=0)
        train_onehot = encode_batch(train_states).to(device)

        # 4. Bellman backup: compute fixed targets J'(s)
        targets = compute_targets(train_states, network, device).to(device)

        # Record outer boundary for saw-tooth plot (except first)
        if outer_iter > 1:
            outer_boundaries.append(len(all_losses))

        # 5. Inner fixed-target training with early stopping
        best_inner_loss = float("inf")
        patience_left = DEEPCUBEA_INNER_PATIENCE

        inner_pbar = tqdm(
            range(1, DEEPCUBEA_INNER_EPOCHS + 1),
            desc="  Inner",
            leave=False,
        )
        for inner_epoch in inner_pbar:
            network.train()
            perm = torch.randperm(len(train_states), device=device)

            total_loss = 0.0
            num_batches = 0

            for i in range(0, len(train_states), DEEPCUBEA_BATCH_SIZE):
                idx = perm[i : i + DEEPCUBEA_BATCH_SIZE]
                batch_x = train_onehot[idx]
                batch_y = targets[idx]

                pred = network(batch_x)
                loss = F.mse_loss(pred, batch_y)

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                total_loss += loss.item()
                num_batches += 1

            avg_loss = total_loss / num_batches
            all_losses.append(avg_loss)

            inner_pbar.set_postfix(
                loss=f"{avg_loss:.6f}",
                best=f"{best_inner_loss:.6f}",
                patience=f"{DEEPCUBEA_INNER_PATIENCE - patience_left}/{DEEPCUBEA_INNER_PATIENCE}",
            )

            if avg_loss < best_inner_loss:
                best_inner_loss = avg_loss
                patience_left = DEEPCUBEA_INNER_PATIENCE
            else:
                patience_left -= 1
                if patience_left == 0:
                    break

        # Save checkpoint after each outer iteration
        torch.save(
            network.state_dict(),
            models_dir / f"deepcubea_heuristic_epoch_{outer_iter}.pt",
        )

        outer_pbar.set_postfix(
            inner_final=f"{avg_loss:.6f}",
            inner_epochs=f"{inner_epoch}/{DEEPCUBEA_INNER_EPOCHS}",
            train_size=f"{len(train_states)}",
        )

    # ── Final save ──
    torch.save(network.state_dict(), models_dir / "deepcubea_heuristic_final.pt")

    # ── Saw-tooth loss curve ──
    plt.figure(figsize=(10, 5))
    plt.plot(all_losses)
    for boundary in outer_boundaries:
        plt.axvline(x=boundary, color="red", linestyle="--", alpha=0.5)
    plt.xlabel("Epoch")
    plt.ylabel("MSE Loss")
    plt.title("DeepCubeA Training Loss (Saw-tooth)")
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(imgs_dir / "loss_curve.png")
    plt.close()

    print(f"Done. {len(all_losses)} total epochs, final loss: {all_losses[-1]:.6f}")
    return network, all_losses


if __name__ == "__main__":
    train()
