"""Shared utilities for DeepCubeA state generation and validation."""

import numpy as np
from deepcubea_network import N, N2, transition

_TRAIN_GOAL = np.arange(N2, dtype=np.int32)


def generate_scrambled_states(n, t_min, t_max, seed=None, start_state=None):
    """Generate n states by random walk from a start state.

    Each state is generated by applying t ~ U(t_min, t_max) random
    actions from the start state (forward walk).

    Args:
        n: number of states to generate
        t_min: minimum scramble steps
        t_max: maximum scramble steps
        seed: random seed
        start_state: (N2,) int32 start state, defaults to training goal

    Returns:
        (n, N2) int32 numpy array of unique states
    """
    if start_state is None:
        start_state = _TRAIN_GOAL
    rng = np.random.default_rng(seed)
    states = []
    for _ in range(n):
        t = rng.integers(t_min, t_max + 1)
        grid = start_state.copy()
        for _ in range(t):
            action = rng.integers(0, 4)
            child = transition(grid, action)
            if child is not None:
                grid = child
        states.append(grid)
    return np.array(states, dtype=np.int32)


def generate_stratified_states(n_total, t_min, t_max, num_strata, seed=None, start_state=None):
    """Generate states stratified by scramble distance K.

    Divides [t_min, t_max] into num_strata equal-width intervals,
    sampling n_total // num_strata states from each.

    Args:
        n_total: total number of states
        t_min: minimum scramble steps
        t_max: maximum scramble steps
        num_strata: number of equal-width strata
        seed: random seed
        start_state: (N2,) int32 start state, defaults to training goal

    Returns:
        states: (n_total, N2) int32 numpy array
        k_values: (n_total,) int32 array of K values per state
        strata_bounds: list of (lo, hi) tuples for each stratum
    """
    if start_state is None:
        start_state = _TRAIN_GOAL
    rng = np.random.default_rng(seed)
    step = (t_max - t_min + 1) / num_strata
    per_stratum = n_total // num_strata

    states = []
    k_values = []
    strata_bounds = []

    for i in range(num_strata):
        lo = int(t_min + i * step)
        hi = int(t_min + (i + 1) * step) - 1
        strata_bounds.append((lo, hi))

        for _ in range(per_stratum):
            k = rng.integers(lo, hi + 1)
            grid = start_state.copy()
            for _ in range(k):
                action = rng.integers(0, 4)
                child = transition(grid, action)
                if child is not None:
                    grid = child
            states.append(grid)
            k_values.append(k)

    return (
        np.array(states, dtype=np.int32),
        np.array(k_values, dtype=np.int32),
        strata_bounds,
    )
