"""DeepCubeA approximate value iteration training.

Trains a DNN J(s) to approximate the optimal cost-to-go via
Bellman backup: J'(s) = min_{a in legal(s)} [1 + J(A(s,a))].

Training data is generated by reverse random walks from the goal state.
"""

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from datetime import datetime
from pathlib import Path
from config import (
    DEEPCUBEA_T_MIN,
    DEEPCUBEA_T_MAX,
    DEEPCUBEA_TRAIN_SET_SIZE,
    DEEPCUBEA_LR,
    DEEPCUBEA_BATCH_SIZE,
    DEEPCUBEA_ITERATIONS,
    DEEPCUBEA_USE_GPU,
    DEEPCUBEA_CHECKPOINT_INTERVAL,
    HUARONGDAO_N,
)
from deepcubea_network import (
    encode_batch,
    transition,
    DeepCubeANetwork,
    N,
    N2,
    INPUT_DIM,
)

GOAL_STATE = np.arange(N2, dtype=np.int32)

_DR = np.array([-1, 1, 0, 0])
_DC = np.array([0, 0, -1, 1])


def _legal_actions(grid_flat):
    """Return list of legal action indices for a grid."""
    idx = int(np.where(grid_flat == 0)[0][0])
    r, c = idx // N, idx % N
    actions = []
    for a in range(4):
        nr, nc = r + _DR[a], c + _DC[a]
        if 0 <= nr < N and 0 <= nc < N:
            actions.append(a)
    return actions


def generate_training_data(n_states, t_min, t_max, seed=None):
    """Generate training states by reverse random walks from the goal state.

    Args:
        n_states: target number of states (includes goal state).
        t_min, t_max: uniform range for random walk length.
        seed: RNG seed for reproducibility.

    Returns:
        (n_states, N2) numpy int32 array of flat grid states.
    """
    rng = np.random.default_rng(seed)
    states = [GOAL_STATE.copy()]

    while len(states) < n_states:
        t = rng.integers(t_min, t_max + 1)
        current = GOAL_STATE.copy()
        for _ in range(t):
            actions = _legal_actions(current)
            a = actions[rng.integers(len(actions))]
            current = transition(current, a)
        states.append(current.copy())

    return np.array(states[:n_states], dtype=np.int32)


def compute_targets(states, network, device):
    """Compute J'(s) targets for all states using current network.

    J'(s) = 0 for goal state, else min_{legal a} [1 + J(A(s,a))].

    Args:
        states: (B, N2) numpy int32 array.
        network: DeepCubeANetwork on the target device.
        device: torch device.

    Returns:
        (B,) float32 tensor on CPU.
    """
    B = len(states)
    blank_pos = np.argmin(states, axis=1)
    blank_r = blank_pos // N
    blank_c = blank_pos % N

    network.eval()

    with torch.no_grad():
        best_j = np.full(B, np.inf, dtype=np.float32)

        for a in range(4):
            nr = blank_r + _DR[a]
            nc = blank_c + _DC[a]
            legal = (0 <= nr) & (nr < N) & (0 <= nc) & (nc < N)

            if not legal.any():
                continue

            new_idx = nr * N + nc
            legal_idx = np.where(legal)[0]

            next_states = states.copy()
            next_states[legal_idx, blank_pos[legal_idx]] = states[
                legal_idx, new_idx[legal_idx]
            ]
            next_states[legal_idx, new_idx[legal_idx]] = 0

            x = encode_batch(next_states).to(device)
            j_vals = network(x).cpu().numpy()

            best_j[legal] = np.minimum(best_j[legal], j_vals[legal] + 1.0)

    goal_mask = np.all(states == GOAL_STATE, axis=1)
    best_j[goal_mask] = 0.0
    best_j[np.isinf(best_j)] = 0.0

    return torch.from_numpy(best_j).float()


def train():
    device = torch.device(
        "cuda" if DEEPCUBEA_USE_GPU and torch.cuda.is_available() else "cpu"
    )
    print(f"Device: {device}")

    # ── Generate & deduplicate training data ──
    rng = np.random.default_rng(42)
    raw = generate_training_data(
        DEEPCUBEA_TRAIN_SET_SIZE, DEEPCUBEA_T_MIN, DEEPCUBEA_T_MAX, seed=42
    )
    states = np.unique(raw, axis=0)
    print(
        f"Training set: {len(states)} unique states "
        f"(from {len(raw)} raw, T ~ U({DEEPCUBEA_T_MIN}, {DEEPCUBEA_T_MAX}))"
    )
    goal_count = np.sum(np.all(states == GOAL_STATE, axis=1))
    print(f"Goal state present: {goal_count > 0}")

    # ── Results directory ──
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    results_dir = Path("results") / f"train_{timestamp}"
    models_dir = results_dir / "models"
    imgs_dir = results_dir / "imgs"
    models_dir.mkdir(parents=True, exist_ok=True)
    imgs_dir.mkdir(parents=True, exist_ok=True)
    print(f"Results: {results_dir}")

    # ── Pre-encode training states ──
    states_onehot = encode_batch(states).to(device)

    # ── Network & optimizer ──
    network = DeepCubeANetwork().to(device)
    optimizer = torch.optim.Adam(network.parameters(), lr=DEEPCUBEA_LR)

    param_count = sum(p.numel() for p in network.parameters())
    print(f"Parameters: {param_count:,}")

    # ── Training loop ──
    best_loss = float("inf")
    losses = []

    for epoch in range(1, DEEPCUBEA_ITERATIONS + 1):
        targets = compute_targets(states, network, device).to(device)

        network.train()
        perm = torch.randperm(len(states), device=device)

        total_loss = 0.0
        num_batches = 0

        for i in range(0, len(states), DEEPCUBEA_BATCH_SIZE):
            idx = perm[i : i + DEEPCUBEA_BATCH_SIZE]
            batch_x = states_onehot[idx]
            batch_y = targets[idx]

            pred = network(batch_x)
            loss = F.mse_loss(pred, batch_y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            num_batches += 1

        avg_loss = total_loss / num_batches
        losses.append(avg_loss)

        is_best = avg_loss < best_loss
        if is_best:
            best_loss = avg_loss

        if epoch % 100 == 0 or epoch == 1 or is_best:
            marker = " *" if is_best else ""
            print(f"Epoch {epoch:>5}/{DEEPCUBEA_ITERATIONS}  loss={avg_loss:.6f}{marker}")

        if is_best:
            torch.save(
                network.state_dict(), models_dir / "deepcubea_heuristic_best.pt"
            )

        if epoch % DEEPCUBEA_CHECKPOINT_INTERVAL == 0:
            torch.save(
                network.state_dict(),
                models_dir / f"deepcubea_heuristic_epoch_{epoch}.pt",
            )
            plt.figure(figsize=(8, 5))
            plt.plot(losses)
            plt.xlabel("Epoch")
            plt.ylabel("MSE Loss")
            plt.title("DeepCubeA Training Loss")
            plt.grid(True, alpha=0.3)
            plt.tight_layout()
            plt.savefig(imgs_dir / "loss_curve.png")
            plt.close()

    # ── Final save ──
    torch.save(network.state_dict(), models_dir / "deepcubea_heuristic_final.pt")
    plt.figure(figsize=(8, 5))
    plt.plot(losses)
    plt.xlabel("Epoch")
    plt.ylabel("MSE Loss")
    plt.title("DeepCubeA Training Loss")
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(imgs_dir / "loss_curve.png")
    plt.close()

    print(f"Done. Best loss: {best_loss:.6f}")
    return network, losses


if __name__ == "__main__":
    train()
